version: '3.8'

services:
  # PostgreSQL for Product Service
  product-db:
    image: postgres:15-alpine
    container_name: product-postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aniket1999
    ports:
      - "5432:5432"
    volumes:
      - product-data:/var/lib/postgresql/data
      - ./product-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL for Order Service
  order-db:
    image: postgres:15-alpine
    container_name: order-postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aniket1999
    ports:
      - "5433:5432"
    volumes:
      - order-data:/var/lib/postgresql/data
      - ./order-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  product-data:
  order-data:

networks:
  microservices-network:
    driver: bridge
